### ISSUE TITLE
Algorithms Not Referenced in Python Client

### ISSUE THREAD

**Issue by gpetrochenkov-usgs** [neo4j/graph-data-science-client#144]
I am running Neo4j 4.4.5 Community on a docker instance.  I installed the library first via `pip install graphdatascience` and then via `pip install git+https://github.com/neo4j/graph-data-science-client` on a conda python 3.10.2 env.  The library installs but from some reason I am unable to see a reference to the algorithms. (In the documentation it shows you can reference `gds.fastRP` or 'gds.shortestPath.dijkstra.stream' for example but none of these show up.) Oddly enough I can project a graph via the python client and then run astar and yens in the Neo4j browser with no issue.  I have tried both GDS 2.1.4 and 2.1.8 jar plugins.  Please advise.  

![gds_issue](https://user-images.githubusercontent.com/30809186/183515817-a35b6013-ad9d-4ac1-ae42-e0893f300ada.png)

**Comment by adamnsch** [comment]
Hi @gpetrochenkov-usgs,

Due to how the library is built, most methods are inferred under the hood as you type them via a string building scheme, using `__getattr__`. That is why they are not visible when you call `dir()`, but they should all be there.
So even if `gds.shortestPath.dijkstra.stream` is not discoverable with `dir()` you should be able to call it.

Does that make sense? We should perhaps document this somewhere to avoid confusion.

**Comment by gpetrochenkov-usgs** [comment]
Yes that does make sense.  I've had success using it so.  Adding that to the documentation would be helpful.  Although there is parity with what is listed in `gds.list()`, is there a way to change what is yielded and returned in case all the data wasn't necessary?  Sometimes in streaming operations the data passed to the client would understandably freeze the process.

**Comment by adamnsch** [comment]
> Yes that does make sense. I've had success using it so. Adding that to the documentation would be helpful. Although there is parity with what is listed in `gds.list()`, is there a way to change what is yielded and returned in case all the data wasn't necessary? Sometimes in streaming operations the data passed to the client would understandably freeze the process.

Yes, I could imagine we use `gds.list()` in an override implementation of `__dir__` on `GraphDataScience` actually. I've added an internal ticket to add docs for this now though.

At this time there's no support for yielding specific things, but it might come soon :)

Thanks for your feedback @gpetrochenkov-usgs
