### ISSUE TITLE
I tried the example demo but failed..

### ISSUE THREAD

**Issue by cpuwar** [neo4j/graph-data-science-client#150]
Hi
I did the example on the link below.
https://github.com/neo4j/graph-data-science-client/blob/main/examples/fastrp-and-knn.ipynb

And I got the error when it executed the mutate call:
...
result = gds.fastRP.mutate(
    G,
    mutateProperty='embedding',
    embeddingDimension=4,
    relationshipWeightProperty='amount',
    iterationWeights=[0.8, 1, 1, 1]
)
< the return and error >
Required memory for native loading: 515 KiB
Graph named 'purchases' projected
Required memory for running FastRP: 3936 Bytes
Traceback (most recent call last):
  File "/mnt/nvme/pycharm-code/neo4j-gds/gds_test.py", line 79, in <module>
    result = gds.fastRP.mutate(
  File "/mnt/nvme/pycharm-code/neo4j-gds/venv/lib/python3.8/site-packages/graphdatascience/algo/algo_proc_runner.py", line 38, in __call__
    return self._run_procedure(G, config).squeeze()  # type: ignore
  File "/mnt/nvme/pycharm-code/neo4j-gds/venv/lib/python3.8/site-packages/graphdatascience/algo/algo_proc_runner.py", line 22, in _run_procedure
    return self._query_runner.run_query_with_logging(query, params)

**Comment by adamnsch** [comment]
Hi @cpuwar,

We cannot see the actual error, only that it's happening somewhere inside `self._query_runner.run_query_with_logging(query, params)`. Would you be able to provide the full error stack?

Thanks,
Adam

**Comment by cpuwar** [comment]
Ah I am sorry. Pycharm Run window displayed only that part. I found the whole error when I ran the code in terminal:
...
neo4j.exceptions.ClientError: Failed to invoke procedure `gds.fastRP.mutate`: Caused by: java.lang.IllegalArgumentException: Node property `embedding` already exists in the in-memory graph.

Now the message is clear to me. I did run the code several times in the middle of writing and it make the error. Now I ran the example successfully. Thanks for your prompt reply!

**Comment by adamnsch** [comment]
> Ah I am sorry. Pycharm Run window displayed only that part. I found the whole error when I ran the code in terminal: ... neo4j.exceptions.ClientError: Failed to invoke procedure `gds.fastRP.mutate`: Caused by: java.lang.IllegalArgumentException: Node property `embedding` already exists in the in-memory graph.
> 
> Now the message is clear to me. I did run the code several times in the middle of writing and it make the error. Now I ran the example successfully. Thanks for your prompt reply!

Thanks for letting us know, and great to hear things are working smoothly now :relaxed: will close the issue then
