### ISSUE TITLE
gds.degree.stream not respecting orientation?

### ISSUE THREAD

**Issue by bSharpCyclist** [neo4j/graph-data-science-client#181]
**Describe the bug**
I'm trying to reproduce a similar result that I would get in GDS.

**To Reproduce**
_Cypher code:_

```
call gds.graph.project('xdc-test-search', ['Event','Search'], { HAS_SEARCH:{orientation:'REVERSE'}})
call gds.degree.stream('xdc-test-search')
YIELD nodeId, score
return gds.util.asNode(nodeId).search_name_1 as SearchTerm, score As NumberOfSearches
Order by NumberOfSearches Descending, SearchTerm Limit 10;
```

The above returns the Search nodes.

_Python code:_

```
node_projection = ["Event","Search"]
relationship_projection = {"HAS_SEARCH": {"orientation": "REVERSE"}}
G, _ = gds.graph.project("xdc-test-search", node_projection, relationship_projection)
degree_stream = gds.degree.stream(G)
```

degree.stream above is returning the node ids of the Event nodes (other side of direction), even if I were to use G = gds.graph.get("xdc-test-search") and use the projection created with cypher.

I'm sure it's something I'm doing on my end :)

graphdatascience library version: 1.3
GDS plugin version: 2.1.7
Python version: 3.9.12
Neo4j version: 4.4.10
Operating system: macOS 12.6

The image below is what I would expect from the python approach.
![image](https://user-images.githubusercontent.com/20865378/191379168-67c34380-94f8-4e1b-a62e-c2fa2a1b2481.png)

**Comment by adamnsch** [comment]
Hi @bSharpCyclist,

The Python code `gds.degree.stream(G)` is really just calling `call gds.degree.stream('xdc-test-search')` and unpacking the result into a dataframe under the hood, so I'm surprised there's a difference.

What's the code for parsing the result of the Python call to `gds.degree.stream`? How do you know what you see are "Event" nodes?

Adam

**Comment by bSharpCyclist** [comment]
Hi @adamnsch 

Thanks for the response. In the dataframe that is returned from gds.degree.stream there is a column of nodeIds, and a score column of all zeros, which what I would suspect for that direction of the relationship. Events are unique and will only point to one Search configuration node, but a Search node can have many edges coming into it. After using gds.util.asNode(nodeId) on one of the nodeIds and taking a look at that result, I can see that the node is an Event node.

**Comment by bSharpCyclist** [comment]
OMG facepalm, I just assumed they were all event nodes. That's exactly it 😊 Thanks!!
