### ISSUE TITLE
Set target database within initial constructor call

### ISSUE THREAD

**Issue by seankrobinson** [neo4j/graph-data-science-client#190]
**Is your feature request related to a problem? Please describe.**
I would like to set the database I plan to use upon initializing my gds object `GraphDataScience(URI, auth=creds, database='my-db')` rather than having to call `gds.set_database("my-db")`. This would purely be a simple convenience to save a line of code.

**Describe the solution you would like**
Allow the setting of the database within the constructor call

**Comment by adamnsch** [comment]
Thanks for your feature request @seankrobinson! We will discuss it within the team and get back to you shortly.

**Comment by adamnsch** [comment]
Made a PR to implement this: #191

**Comment by adamnsch** [comment]
The feature was included in version 1.4 of the library that was released today.
