### ISSUE TITLE
Relationship Orientation during graph construction with dataframes

### ISSUE THREAD

**Issue by valerio-piccioni** [neo4j/graph-data-science-client#209]
Hi, I'd like to understand if it is possible to construct a graph from data frames without orientation so that I can have an undirected relationship. I see from the schema here https://neo4j.com/docs/graph-data-science/current/graph-project-apache-arrow/#arrow-send-relationships that source and destination are mandatory but there is no special column for orientation.

**Comment by adamnsch** [comment]
> Hi, I'd like to understand if it is possible to construct a graph from data frames without orientation so that I can have an undirected relationship. I see from the schema here https://neo4j.com/docs/graph-data-science/current/graph-project-apache-arrow/#arrow-send-relationships that source and destination are mandatory but there is no special column for orientation.

Hi @valerio-piccioni,

Thanks for reaching out. What you have observed is a limitation in the API. It's not possible to specify orientation, but rather all relationships will be projected as NATURAL (i.e. directed) for now. It's not something we can solve in the Python client surface, but a limitation in the underlying Apache Arrow API that the client uses as you have observed. However, we are aware of this limitation and are planning to remedy this on the server side, and eventually reflect that change also in the `construct` API.

Regards,
Adam

**Comment by valerio-piccioni** [comment]
Ok, I understood, thank you Adam

**Comment by DarthMax** [comment]
Hej @valerio-piccioni!

We will adress this issue in the upcoming releases of GDS and the Python Client.
With GDS 2.3.0 and Python client version 1.6 you will be able to specify which relationship types should be imported as undirected. 
Here is the the pull request that introduces this functionality to the client
https://github.com/neo4j/graph-data-science-client/pull/230

Additionally there will be a procedure that can turn any existing directed relationship type into a new undirected relationship type called `gds.beta.graph.relationships.toUndirected`
https://github.com/neo4j/graph-data-science-client/pull/235
https://neo4j.com/docs/graph-data-science/2.3-preview/graph-catalog-relationship-ops/#_syntax

This cannot be used as of yet but should be available in Q1 2023.

Best, Max
