### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureCallFailed when constructing a GDS graph object from DataFrame

### ISSUE THREAD

**Issue by joyemang33** [neo4j/graph-data-science-client#460]
**Neo4j Version:** 5.10
**Operating System:** Ubuntu 20.04
**API:** Docker

Hello! When I use Graph Data Science to construct a graph with 1 node and 0 relationships, Neo4j throws a strange exception. I believe that this behavior may be unexpected and related to a potential bug since we should allow running some algorithms in the graph without relationships. Could you further confirm and investigate it? It would be highly appreciated!

### Steps to reproduce

Run the following python code:

```python
nodes = pandas.DataFrame(
    {
        "nodeId" : [0],
        "labels" : ["person"],
    }
)

relationships = pandas.DataFrame(
    {
        "sourceNodeId" : [],
        "targetNodeId" : [],
        "relationshipType" : []
    }
)

gds.graph.construct(
    graph_name="my_graph",
    nodes=nodes,
    relationships=relationships
)
```

### Expected behavior
Successfully constructing the graph object.

### Actual behavior
```
Neo.ClientError.Procedure.ProcedureCallFailed
```
**message**: Failed to invoke function `gds.graph.project`: Caused by: ```java.lang.IllegalArgumentException```: The node has to be either a NODE or an INTEGER, but got Double.

**Comment by Mats-SX** [comment]
Hello @joyemang33 and thanks for reaching out to us!

I believe the issue in this case is with the schema inference of the relationships dataframe. Since the arrays are empty, Pandas cannot know what `dtype` to select for each of the columns. Thus, the default `Float64` type is used. On the GDS side, we validate that the values must be NODE or INTEGER, and the dataframe is rejected.

```
relationships = DataFrame(
        {
            "sourceNodeId": [],
            "targetNodeId": [],
            "relationshipType": []
        }
    )
    
    print(relationships.dtypes)
```

```

A way to get past this situation is to manually set the `dtype` of the columns to `Int64`. I don't know exactly how to do it, but something like

**Comment by FlorentinD** [comment]
Even easier you can just pass an empty list of relationships, then we wont even try to interfere the types

```
gds.graph.construct(
    graph_name="my_graph",
    nodes=nodes,
    relationships=[]
)
```

**Comment by Mats-SX** [comment]
OK I tested now and I can conclude that @FlorentinD's suggestion is the better one. It will work regardless of whether you have Arrow configured (EE feature) or not. My solution only works when you _do not_ have Arrow configured.

I don't there is any bug here, so I'm closing the issue. I hope you have been unblocked and can continue your work.

All the best
Mats

**Comment by FlorentinD** [comment]
Reopening the issue as we can just ignore empty dfs in the input

**Comment by joyemang33** [comment]
> Reopening the issue as we can just ignore empty pdfs in the input

Thank you all @Mats-SX @FlorentinD for your so quick responses and fixes.
In my opinion, it is a bug because this exception looks like confusion for users, and the following Python code (both empty nodes and relationships) **will not** cause such exceptions.
```python
nodes = pandas.DataFrame(
    {
        "nodeId" : [],
        "labels" : [],
    }
)

relationships = pandas.DataFrame(
    {
        "sourceNodeId" : [],
        "targetNodeId" : [],
        "relationshipType" : []
    }
)

gds.graph.construct(
    graph_name="my_graph",
    nodes=nodes,
    relationships=relationships
)
```

I think https://github.com/neo4j/graph-data-science-client/pull/461 is a good solution for that case (filtering the empty relationships before the executions), improving the robustness of GDS and mitigating the inconsistency between the two cases (*a.* only empty relationships and *b.* both empty nodes and relationships).

Thanks once again for your kind responses and fixes! 

Best regards,
Joye
