### ISSUE TITLE
issue when running the example kge-predict-transe-pyg-train.ipynb

### ISSUE THREAD

**Issue by ladwis** [neo4j/graph-data-science-client#554]
**Describe the bug**
 In the Jupyter notebook of "_kge-predict-transe-pyg-train.ipynb_",  the function _**create_data_from_graph(relationship_type)**_ doesn't produce the result expected.  Instead, an error occurs with the message   _**Index contains duplicate entries, cannot reshape**_  when calling the function **_train_tensor_data = create_data_from_graph(["TRAIN"]_**. Plus, "TRAIN" must be between square brackets "[]". 

**To Reproduce**

graphdatascience library version: X.Y
GDS plugin version: X.Y.Z
Python version: X.Y.Z
Neo4j version: X.Y.Z
Operating system: (for example Windows 95/Ubuntu 16.04)

- [ ] Graph/dataset to reproduce the bug.  Alternatively describe as much as possible the data, e.g., graph size and other schema/structure details.
- [ ] Python code
- [ ] Other queries not run through the python client

**Expected behavior**

**Additional context**

**Comment by orazve** [comment]
Hello,

Did you use the example notebook without any changes? If you have changes, could you please show the minimal working example to reproduce the problem and full error message with stack trace?

Additionally, could you please provide information regarding the versions of the software you are using, including the GDS Python client, GDS, Neo4j, Python, and Pandas versions?

**Comment by adamnsch** [comment]
I'll also add that we run this notebook daily in as part of our testing, and there it works fine.

**Comment by adamnsch** [comment]
This issue will be closed due to inactivity. @ladwis please feel free to reopen the issue if need be. Thank you
