### ISSUE TITLE
nodeLabels are not returned appropriately 

### ISSUE THREAD

**Issue by Hossein-Tohidi** [neo4j/graph-data-science-client#563]
When a gds graph is constructed using gds.graph.construct, the nodeLabels are not returned appropriately. 

```python 
nodes_df = pd.DataFrame([[1, 'Paper',11],[2,'Paper',22]], columns=['nodeId','labels','topic'])  
edges_df = pd.DataFrame([[1,2,'Cites']], columns = ['sourceNodeId','targetNodeId','relationshipType'])  
G = gds.graph.construct("test", nodes_df, edges_df)  
print(gds.graph.nodeProperties.stream(G, ["topic"]))  
# results 
#	nodeId	nodeProperty	propertyValue	nodeLabels
#0	1	topic	11	[]
#1	2	topic	22	[]

**Comment by FlorentinD** [comment]
@Hossein-Tohidi , thank you for reporting this issue.
I could further see, that it only occurs with the Arrow endpoint.

As an intermediate workaround, you could initialize the client with `arrow=False`.
You can track the progress at #564

**Comment by Hossein-Tohidi** [comment]
I just realized that it is not working with separate_property_columns=True, option!

**Comment by FlorentinD** [comment]
Looking through your edits, it looks like specifying `listNodeLabels=True` as well?
As the default is `False`, it makes sense this column is only present if you set it explicitly (see https://neo4j.com/docs/graph-data-science/current/management-ops/graph-reads/graph-stream-nodes/).

**Comment by Hossein-Tohidi** [comment]
Thanks again for your reply. 
The following code, I expect to return the nodeLabels as well but it does not (it should be part of the column we pivot on that to get a wide table from a long table, I guess). 

```python
print(gds.graph.nodeProperties.stream(G, ["twl",'twu'],listNodeLabels=True, separate_property_columns=True))  
#   nodeId  twl   twu
#0       0  0.0   7.0
#1       1  0.0  20.0
#2       2  0.0  20.0

**Comment by FlorentinD** [comment]
Thanks for this find as well. We definitely missed out on tests for this feature on the client side :/ 

The PR is ready for review now with this fix as well.

The actual workaround for now it to not use `arrow=False` + `separate_property_columns=True` and widen the result yourself.
You can find the logic for this [here](https://github.com/neo4j/graph-data-science-client/blob/44356a0bf9937ffb8ae3b357810e655ea544ca43/graphdatascience/graph/graph_entity_ops_runner.py#L90).
Maybe you even have an idea for a better version?

**Comment by Hossein-Tohidi** [comment]
Thanks @FlorentinD, the logic you referred to makes sense to me and it works fine.
