### ISSUE TITLE
uri keyword parameter missing

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science-client#598]
They uri keyword parameter is missing for GraphDataScience and Neo4j python client, it creates an inconsistancy, so you cannot use **credentials unpaking in python to spreed all credentials parameters at once.

As an example, with this beauty:

credentials = {
'uri':'bolt://data.test.com',
'auth':('user,'password'),
'database':'test'
}

We could simply run:

GraphDataScience(**credentials)

Instead we have to do this mess because uri keyword is missing and not consistant with the keyword pattern.

GraphDataScience(credentials['uri'], auth= credentials['auth'], database= credentials['database'])

**Comment by adamnsch** [comment]
Hi @Mintactus,

Thank you for your feature request. In general we are not strictly adhering to the conventions of the Neo4j Python driver, but I have made a PR to fulfil your request: https://github.com/neo4j/graph-data-science-client/pull/599. Please note that the parameter is called `endpoint` and not `uri` however, as this parameter represents more than just a URI.

Adam

**Comment by Mintactus** [comment]
Thanks for your consideration, I made a mistake, Neo4j driver is also not
specifying the uri keyword parameter, so they are both aligned in that
sense.
But still having a keyword parameter like endpoint would allow us to use
the python unpacking syntax properly like this **credentials for both gds
and neo4j driver.

Thanks

**Comment by adamnsch** [comment]
Hi again,

Yes, I agree that it's nice to allow for the **kwargs unpacking. The PR is merged now and the changes will be part of the next release of the library, which will be 1.10.

Thank you again for your feedback. I'm closing this issue now.
